# Generated by Django 5.2.3 on 2025-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_friday_hours', models.CharField(default='9am to 20 pm', max_length=50)),
                ('saturday_hours', models.CharField(default='9am to 17 pm', max_length=50)),
                ('vacation_days', models.TextField(default='All Sunday Days\nAll Official Holidays')),
            ],
            options={
                'verbose_name_plural': 'Business Hours',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_subheading', models.CharField(default='Welcome to Cleaning Company', max_length=100)),
                ('welcome_heading', models.CharField(default="Let's make you fresher than ever", max_length=200)),
                ('description', models.TextField(default='Far far away, behind the word mountains...')),
            ],
            options={
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='CounterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.IntegerField(default=45)),
                ('happy_customers', models.IntegerField(default=2342)),
                ('buildings_cleaned', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': 'Counter Statistics',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='(+01) 123 456 7890', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
    ]
