# Generated by Django 5.2.3 on 2025-06-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0003_businesshours_companyinfo_counterstat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterstat',
            old_name='buildings_cleaned',
            new_name='service_deliver',
        ),
    ]
