# Generated by Django 5.2.3 on 2025-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0004_rename_buildings_cleaned_counterstat_service_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='image',
            field=models.ImageField(default='company_images/default.jpg', upload_to='company_images/'),
        ),
    ]
