# Generated by Django 5.2.3 on 2025-06-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0005_companyinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 9, 19, 0, 38876, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesshours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 9, 19, 15, 318649, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='counterstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 9, 19, 19, 598537, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 9, 19, 23, 110710, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='monday_friday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='welcome_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='welcome_subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counterstat',
            name='happy_customers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='counterstat',
            name='service_deliver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='counterstat',
            name='years_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
