# Generated by Django 5.2.3 on 2025-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0006_businesshours_created_at_businesshours_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
