# Generated by Django 5.2.3 on 2025-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0007_service_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
