# Generated by Django 5.2.3 on 2025-06-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0008_alter_service_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='monday_friday_hours',
            new_name='working_hours',
        ),
    ]
