# Generated by Django 5.2.3 on 2025-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0009_rename_monday_friday_hours_businesshours_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('pest_control', 'Pest Control'), ('cleaning', 'Cleaning')], default='cleaning', max_length=20),
        ),
    ]
