# Generated by Django 5.2.3 on 2025-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0010_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
    ]
