# Generated by Django 5.2.3 on 2025-06-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0015_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='google',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
