# Generated by Django 5.2.3 on 2025-06-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0016_emergencycontact_address_emergencycontact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInfo',
            new_name='AboutInfo',
        ),
    ]
