# Generated by Django 5.2.3 on 2025-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0017_rename_companyinfo_aboutinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='CounterStat',
        ),
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name_plural': 'About Info'},
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='happy_customers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='service_deliver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='vacation_days',
            field=models.TextField(default='All Sunday Days\nAll Official Holidays'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
