# Generated by Django 5.2.3 on 2025-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0020_introsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introsection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='introsection',
            name='video_link',
        ),
        migrations.AddField(
            model_name='introsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)', null=True),
        ),
    ]
