# Generated by Django 5.2.3 on 2025-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_services', '0023_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Pest Control', 'Pest Control'), ('Cleaning', 'Cleaning')], default='cleaning', max_length=20),
        ),
    ]
